#!/bin/sh

if [ "$1" = "purge" ]; then
    update-rc.d teamcity-agent remove >/dev/null
    userdel teamcity || true
    groupdel teamcity || true
    rm -rf /var/lib/teamcity-agent /var/log/teamcity-agent /var/run/teamcity-agent
fi

