#!/bin/sh
#
# Start and stop the TeamCity Build Agent
#
#chkconfig: 2345 80 05
#description: TeamCity Build Agent
### BEGIN INIT INFO
# Provides: teamcity-agent
# Required-Start: $network $remote_fs
# Required-Stop: $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: TeamCity Build Agent
### END INIT INFO

umask 002

mkdir -p /var/run/teamcity-agent
chown -R teamcity:teamcity /var/run/teamcity-agent
chmod -R 750 /var/run/teamcity-agent

check_stopped() {
  $0 status
  until [ $? -ne 0 ]; do
    sleep 1
    $0 status
  done
  sleep 3
}

case "$1" in
  start)
    /bin/su - teamcity -c "/usr/share/teamcity-agent/agent.sh $1"
    RETVAL=$?
    ;;
  stop)
    /bin/su - teamcity -c "/usr/share/teamcity-agent/agent.sh $1"
    RETVAL=$?
    ;;
  restart)
    $0 stop
    check_stopped
    $0 start
    RETVAL=$?
    ;;
  reload)
    ;;
  force-reload)
    ;;
  status)
    /bin/su - teamcity -c "/usr/share/teamcity-agent/agent.sh $1"
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 { start | stop | restart | reload | force-reload | status }"
    exit 1
    ;;
esac
exit ${RETVAL}

