#!/bin/sh
#
# Start and stop the TeamCity Build Agent
#
#chkconfig: 2345 80 05
#description: TeamCity Build Agent
### BEGIN INIT INFO
# Provides: teamcity-agent
# Required-Start: $network $remote_fs
# Required-Stop: $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: TeamCity Build Agent
### END INIT INFO

umask 002

case "$1" in
  start)
    /bin/su - teamcity -c "/usr/share/teamcity-agent/agent.sh $1"
    RETVAL=$?
    ;;
  stop)
    /bin/su - teamcity -c "/usr/share/teamcity-agent/agent.sh $1"
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 { start | stop }"
    exit 1
    ;;
esac
exit ${RETVAL}

